<Project Sdk="Aspire.AppHost.Sdk/13.5.3">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>5e85e8bf-b79a-4761-8e1f-e6a0b700843c</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" />
    <PackageReference Include="Aspire.Hosting.RabbitMQ" />
    <PackageReference Include="CommunityToolkit.Aspire.Hosting.Ollama" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MarketplaceRegulationAgent.Api\MarketplaceRegulationAgent.Api.csproj" />
    <ProjectReference Include="..\MarketplaceRegulationAgent.ValidationWorker\MarketplaceRegulationAgent.ValidationWorker.csproj" />
  </ItemGroup>

</Project>
